### ISSUE TITLE
Run `test.sh` error

### ISSUE THREAD

**Issue by QuinzyW** [qurAI-amsterdam/airogs-example-algorithm#1]
Dear Organizer:
I follow the tutorial from Github with Ubuntu and have met some problems. It's successfully to create Docker but something wrong with `json.decoder.JSONDecodeError:`.
![92cd1f15a8202d8142c46b8dcfcb02c](https://user-images.githubusercontent.com/41409166/146661384-49a874d6-f913-4461-854a-97a7c20c0e8b.png)

**Comment by coendevente** [comment]
Thank you for pointing out this issue. I just checked and it seems git LFS caused some issues with the json files in `/test`. If you now pull the new changes I just pushed, you should not get this error anymore.

Please let me know whether this helped.

**Comment by QuinzyW** [comment]
thanks for your help, the question has been solved. ![fine](https://cdn.jsdelivr.net/gh/wangxiatian/picture@main/image/16400507271471640050700.jpg)
