### ISSUE TITLE
Data should be converted to string before being dumped as json

### ISSUE THREAD

**Issue by mike1nz** [qurAI-amsterdam/airogs-example-algorithm#2]
Hi, lines 65-70 of process.py could be changed to:
```
out = {
            "referable-glaucoma-likelihood": str(rg_likelihood), 
            "referable-glaucoma-binary": str(rg_binary),  
            "ungradability-score": str(ungradability_score), 
            "ungradability-binary": str(ungradability_binary)  
        }
```
When rg_likelihood is a very small number, e.g. 2.7446868e-14, json.dump raises a value error. Interestingly this error is not raised for other numbers, e.g 0.0. Hence some examples may generate exceptions while others don't depending on what numbers your model outputs. Converting everything to string before calling json.dump seems to fix the problem.

**Comment by coendevente** [comment]
Writing a JSON file with 2.7446868e-14 as float (so not as string) works for me. Are you sure the addition of str solved the error or did you change something else as well?

Does running this simple script work for you:
```
with open('test.json', 'w') as f:
    json.dump(2.7446868e-14, f)
```

Converting everything to strings will cause later issues when evaluating on grand-challenge.

**Comment by mike1nz** [comment]
Good point, that test works OK. I'll look into it and see if there's another cause for the value error.

**Comment by mike1nz** [comment]
OK, the issue was that numpy float32s are not serialisable into json. The solution is to convert them to string, then eval them back into a python float.

```
import json
import numpy as np
x=np.float32(2.7446868e-14)
with open('test.json', 'w') as f:
     json.dump(x, f)
# Causes: TypeError: Object of type float32 is not JSON serializable
with open('test.json', 'w') as f:
     json.dump(eval(str(x)), f)
# OK

```
Relevant discussion is here: https://stackoverflow.com/questions/53082708/typeerror-object-of-type-float32-is-not-json-serializable

**Comment by coendevente** [comment]
Good, that it's solved! One minor thing, I think `float(x)` should also work instead of `eval(str(x))`.
